### ISSUE TITLE
calc() + var() call not compiling without an extra space?

### ISSUE THREAD

**Issue by Anahkiasen** [NMFR/optimize-css-assets-webpack-plugin#119]
I have this line in a dependency's CSS (basscss):

```css
.mxn1{ margin-left:-0.5rem; margin-left:calc(var(--space-1)*-1); }
```

If I try to build I get a Parse Error. If however I do this (spaces around the *):

```css
.mxn1{ margin-left:-0.5rem; margin-left:calc(var(--space-1) * -1); }
```

It compiles fine. Not sure what's wrong with the syntax either way :s This only happens when minification is active so it doesn't come from PostCSS or something else as far as I can tell. Here's a reproduction repository if it helps https://github.com/Anahkiasen/minification-issue-test

As far as I can tell substituing the var() call with its value compiles, so it's really the combo of var + cal + *-1 but not sure why
