### ISSUE TITLE
Incorrect transformation with semi transparent composited radial gradient

### ISSUE THREAD

**Issue by zero298** [NMFR/optimize-css-assets-webpack-plugin#30]
I believe there may be an issue with how radial gradients are optimized.  I'm using the configuration produced by vue-cli.  If I comment out the `OptimizeCSSPlugin` block, I don't get the issue.

```js
new OptimizeCSSPlugin({
  cssProcessorOptions: config.build.productionSourceMap
    ? { safe: true, map: { inline: false } }
    : { safe: true }
}),
```

--------

My expected result, which I get if I turn off the optimizer, is a composited background that has a semi-transparent orange radial gradient on top of a blue to black linear gradient:

```css
.original {
    background:
        radial-gradient(ellipse 200% 100% at top left 40%, rgba(255, 169, 0, 0.5), transparent 30%),
        linear-gradient(45deg, black 20%, #002f76);
}
```

<img width="1163" alt="screen shot 2018-01-25 at 11 53 14 am" src="https://user-images.githubusercontent.com/325543/35404135-7ff92036-01c7-11e8-85b3-4da64063b227.png">

If I enable the optimizer, only the blue to black gradient is visible:

```css
.output {
    background:
        radial-gradient(ellipse 200% 100% at top left 40%, rgba(255, 169, 0, .2), transparent 0),
        linear-gradient(45deg, #000 20%, #002f76);
}
```

<img width="1035" alt="screen shot 2018-01-25 at 12 00 44 pm" src="https://user-images.githubusercontent.com/325543/35404184-ad8a80da-01c7-11e8-8d55-148293d6e5f3.png">

I believe it is because the `color-stop` of the radial gradient is being changed for the second color from `transparent 30%` to `transparent 0`.  I'm not sure why.
