### ISSUE TITLE
Not compatible with webpack's css-loader css-modules option

### ISSUE THREAD

**Issue by moog16** [NMFR/optimize-css-assets-webpack-plugin#42]
My webpack config:

```js
...

{
  test: /\.scss$/,
    use: ExtractTextPlugin.extract({
      use: [{
        loader: 'css-loader',
          options: {
            modules: true,  // this turns on css modules via the css-loader
            importLoaders: 2,
            localIdentName: '[sha1:hash:hex:4]',
          },
       }, { /** sass-loader config **/ }]
    }]
}

...


plugins: [
  new ExtractTextPlugin('bundle.css'),
  new OptimizeCssAssetsPlugin(),
]
```

I noticed when I build w/o the OptimizeCssAssetsPlugin, there is some sass variable that gets wrapped in a `:local()` function (documentation found [here](https://github.com/webpack-contrib/css-loader#scope)).

With OptimizeCssAssetsPlugin returns me this error:

```
Error processing file: bundle.css
CssSyntaxError: /bundle.css:315:18: Missed semicolon
    at Input.error (/node_modules/postcss/lib/input.js:113:22)
    at Parser.checkMissedSemicolon /node_modules/postcss/lib/parser.js:506:26)
```

I went to bundle.css:315:18:

```css
.e127.f18c::after,
._77c2.f18c::after {
      animation: 225ms :local(my-scss-variable) forwards, 75ms :local(my-scss-variable) forwards; }
```

I think its the cssnano lib getting hung up on the `:local` wrapper. Any ideas of a work around?
